alternate: Giane # 站点大标题
#  静态资源和标题
statics: "/" # 静态文件根目录，可用于CDN加速
assets: "assets" # 图片资源存放目录
css: "css" # css存放目录(不建议改动)
js: "js" # js存放目录(不建议改动)

# 侧边栏和导航
menu:
  home: / || home
  about:
    default: / || user
    aboutsite: /about/  || user
    admiration: /admiration/ || coffee
  posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
  friends: /friends/ || heart

# 边栏设置
sidebar:
  position: left # right
  avatar: avatar.jpg

# 开启后在页面底部显示随机文章和最近评论
widgets:
  random_posts: true # 随机文章
  recent_comments: false # 显示最近评论

# 页尾全站统计
footer:
  since: 2023 # 开始时间
  count: true # 开启
  powered: "Powered by ChanningE"
  icp: "112233" # ICP备案
  enable: true
  icon: "" #网安备案图片
  icpnumber: "xxx" # ICP备案号
  beian: "xxx" # 网安备案号
  recordcode: "xxx" # 网安备案链接中的recordcode参数
# 文章界面统计
post:
  count: true # 开启

# Algolia Search
# For more information: https://www.algolia.com
search:
  hits:
    per_page: 10


# Reward (Donate)
reward:
  # If true, reward will be displayed in every article by default.
  enable: true
  account:
    wechatpay: /wechatpay.png
    alipay: /alipay.png
    paypal: /paypal.png

# TagCloud settings for tags page.
tagcloud:
  # All values below are same as default, change them by yourself.
  min: 16 # Minimun font size in px
  max: 22 # Maxium font size in px
  start: "#72cecf" # Start color (hex, rgba, hsla or color keywords)
  end: "#ffbac3" # End color (hex, rgba, hsla or color keywords)
  amount: 200 # Amount of tags, change it if you have more than 200 tags

performance:
  # 使用preconnect预加载的网址(不建议超过三个)
  # preConnect:
  #  - "https://lf9-cdn-tos.bytecdntp.com"
  # 使用dns-prefetch预解析的网址
  dnsPrefetch:
    - "https://cdn.jsdelivr.net"
    - "https://unpkg.com"

seo:
  bing:
  google:
  yandex:
  baidu:

visitor:
  clarity: false
  baiduAnalytics: false
  googleAnalytics: false

darkmode: true
auto_dark: # 自动亮/暗模式
  enable: true #是否开启
  start: 20 #开始时间
  end: 7 #结束时间

auto_scroll: false

loader:
  start: true # 进入页面时显示加载动画
  switch: false # 切换页面时显示加载动画

# 音乐播放器
audio:
  - title: my love
    list:
      - https://music.163.com/#/playlist?id=2943811283
      - https://music.163.com/#/playlist?id=2297706586
#  - title: 列表2
#    list:
#      - https://music.163.com/#/playlist?id=2031842656

# 社交连接
social:
  # github: https://github.com/name || github || "#191717"
  # google: https://plus.google.com/yourname || google
  # twitter: https://twitter.com/yourname || twitter || "#00aff0"
  # zhihu: https://www.zhihu.com/people/yourname || zhihu || "#1e88e5"
  # music: https://music.163.com/#/user/home?id=yourid || cloud-music || "#e60026"
  # weibo: https://weibo.com/yourname || weibo || "#ea716e"
  # about: https://about.me/yourname || address-card || "#3b5998"
  email: mailto:foo@xxx.com || envelope || "#55acd5"
  facebook: https://www.facebook.com/giane || facebook
  # stackoverflow: https://stackoverflow.com/ || stack-overflow
  # youtube: https://youtube.com/yourname || youtube
  # instagram: https://instagram.com/yourname || instagram
  # skype: skype:yourname?call|chat || skype
  # douban: https://www.douban.com/people/yourname/ || douban

# 实验性特性
experiments:
  noIE: true # TODO 阻止IE浏览器访问(ShokaX不支持IE的任何版本)
  noPlayer: false # 禁用音乐播放器
  gradient: false # 使用CSS渐变作为文章封面
  fixedCover: "" # 主页面cover(为空则使用bing随机图片)

markdown:
  render: # 渲染器设置
    html: false # 过滤 HTML 标签
    xhtmlOut: true # 使用 '/' 来闭合单标签 （比如 <br />）。
    breaks: true # 转换段落里的 '\n' 到 <br>。
    linkify: true # 将类似 URL 的文本自动转换为链接。
    typographer:
    quotes: "“”‘’"
  plugins: # markdown-it 插件设置
    - plugin:
        name: markdown-it-toc-and-anchor
        enable: true
        options: # 文章目录以及锚点应用的 class 名称，shoka 系主题必须设置成这样
          tocClassName: "toc"
          anchorClassName: "anchor"
    - plugin:
        name: markdown-it-multimd-table
        enable: true
        options:
          multiline: true
          rowspan: true
          headerless: true
    - plugin:
        name: ./markdown-it-furigana
        enable: true
        options:
          fallbackParens: "()"
    - plugin:
        name: ./markdown-it-spoiler
        enable: true
        options:
          title: "你知道得太多了"

autoprefixer:
  exclude:
    - "*.min.css"

highlight:
  enable: false

prismjs:
  enable: false

syntax_highlighter: false
